name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  # или другая основная ветка
  workflow_dispatch:  # ручная активация через интерфейс GitHub

jobs:
  setup:
    name: Setup MkDocs Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Checkout
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Python install
        run: pip install -r requirements.txt

      - name: MkDocs Build
        run: mkdocs gh-deploy --force --clean --verbose 
