name: Deploy MkDocs Site

on:
  push:
    branches:
      - main  # или другая основная ветка
  workflow_dispatch:  # ручная активация через интерфейс GitHub

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: main
      
      - name: Test
        run: cd ./main && echo "$(cat README.md)"

      - name: Test2
        run: cd ./main && echo "$(cat requirements.txt)"

      - name: Test3
        run: cd ./main && ls -la
